### ISSUE TITLE
setclaimflag inside subdivisionclaim

### ISSUE THREAD

**Issue by comonier** [akdukaan/GPFlags#37]
**GPFlagVersion**: `GPFlags-5.12.5`

**Plugins:** Plugins (57): AntiWorldFly, AutoRestart*, BanFromClaim, BetterRTP, BlockLocker, CMILib, DiscordSRV, Elevator, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, F3Name, FastLogin, floodgate, GPFlags, GPTeleport, GriefPrevention, InteractiveChat, JDALibLoaderBukkit, Jobs, KickFromClaim, Leashable, mcMMO, MineableSpawners, MobFarmManager, Multiverse-Core, MVdWPlaceholderAPI*, NBTAPI, Orebfuscator, OtherAnimalTeleport, PermissionsEx*, PEXChat*, PlaceholderAPI, PlayerWarps, PlugMan, PortalBlockerFree, ProtocolLib, QuickShop, RealEstate, ShopGUIPlus, ShopGUIPlus-SellGUI, ShopGUIPlusMineableSpawnersBridge, SimpleClans, Slimefun, TAB, Themis, UltimateChat, UnbreakableLeashes, Vault, ViaBackwards, ViaVersion, VoidSpawn, Vote*, Votifier, WorldEdit, WorldGuard

**Version**:  
```java
> version
[11:28:43 INFO]: Checking version, please wait...
[11:28:43 INFO]: This server is running Paper version git-Paper-364 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: fa42c68)
You are 20 version(s) behind
Download the new version at: https://papermc.io/downloads
```
**Error on console**:
```yaml
[11:25:24 INFO]: comonier issued server command: /setclaimflag OwnerMemberFly true
[11:25:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'setclaimflag' in plugin GPFlags v5.12.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.3.jar:git-Paper-364]
        at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-364]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2288) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-364]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-364]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.ryanhamshire.GriefPrevention.Claim.getGreaterBoundaryCorner()" because "claim" is null
        at me.ryanhamshire.GPFlags.util.Util.getPlayersIn(Util.java:499) ~[GPFlags-5.12.5.jar:?]
        at me.ryanhamshire.GPFlags.flags.FlagDef_OwnerMemberFly.onFlagSet(FlagDef_OwnerMemberFly.java:30) ~[GPFlags-5.12.5.jar:?]
        at me.ryanhamshire.GPFlags.FlagManager.setFlag(FlagManager.java:137) ~[GPFlags-5.12.5.jar:?]
        at me.ryanhamshire.GPFlags.commands.CommandSetClaimFlag.onCommand(CommandSetClaimFlag.java:125) ~[GPFlags-5.12.5.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

**Comment by comonier** [comment]
![image](https://user-images.githubusercontent.com/19571541/214874674-e14f2bd6-96da-42da-b2fb-1746e9431919.png)

WELL - BUT IT WORKS - it sends error - but still working

**Comment by akdukaan** [comment]
You can update to the [dev builds](https://jenkins.akiradev.xyz/job/GPFlags/) for a partial fix. The partial fix will hide the message but won't automatically activate fly when the flag is set. The full fix requires https://github.com/TechFortress/GriefPrevention/pull/2011
